# NumPy (short for Numerical Python)  


- ### NumPy arrays


In [ ]:
first = np.array([1, 2, 3, 4, 5])
print(first)                       # [1 2 3 4 5]
print(type(first))                 # <class 'numpy.ndarray'>

In the example above, first is a one-dimensional array that is treated as a vector. As you can see, when printed, it is rendered without commas, as opposed to Python lists.



- You can also use not only integers in the list but any objects (strings, lists, etc.) by specifying the dtype argument as object(Python object, since in this example you have int, str, and listas element types):

In [ ]:
first_modified = np.array(['1', 2, [3], 4, [5]], dtype=object)
print(first_modified)  # ['1' 2 list([3]) 4 list([5])]

## `NumPy arrays vs Python lists`

- Unlike Python lists, which can contain objects of different types(a property known as heterogeneity), the objects in NumPy arrays with different Python types will be of the same type — thedtype. This property is referred to as homogeneity, where all elements in the array have the same type, and homogeneity is enforced for performance optimization(operations would be inefficient otherwise). It means that you still can have multiple Python datatypes inside a NumPy array, but they all will be of the object type we mentioned earlier. By default, the dtype will be set to the minimum type required to hold all objects in the sequence.
- NumPy arrays are much more memory-efficient and much faster than Python lists when working with large datasets due to various optimizations.
- ```Arithmetic operations``` `differ` when executed on Python lists or NumPy arrays.

### `Array range and evenly spaced array`

- The first function that helps to create arrays in NumPy, is np.arange(). It is similar to the built-in range() generator of numbers, but np.arange() returns an array. Let's have a look at the example.

In [ ]:
array_1 = np.arange(5)
print(array_1)  # [0 1 2 3 4]

You can also create an array by specifying a start element, a stop element, and a step: np.arange(start, stop, step)

In [ ]:
array_2 = np.arange(5, 9)
array_3 = np.arange(5, 6, 0.2)
print(array_2)  # [5 6 7 8]
print(array_3)  # [5. 5.2 5.4 5.6 5.8]

## `Arrays filled with ones and zeros`

In [ ]:
array_6 = np.ones((3, 2))
array_7 = np.zeros(7)
print(array_6)
# [[1. 1.]
#  [1. 1.]
#  [1. 1.]]
print(array_7)  # [0. 0. 0. 0. 0. 0. 0.]

The "`np.zeros_like()`" and "`np.ones_like()`" functions are similar to the previous ones, but they return an array of ones or zeros with the same shape and type as the given arrays.

In [ ]:
x = np.array([[1, 1, 1], [2, 2, 2]])
y = np.array([1, 2, 3, 4, 5])
array_8 = np.ones_like(x)
array_9 = np.zeros_like(y)
print(array_8)
# [[1 1 1]
#  [1 1 1]]
print(array_9)  # [0 0 0 0 0]

### `Converting NumPy arrays to Python lists`

In [ ]:
array_10 = np.array([[1, 2], [3, 4]])
lst1 = array_10.tolist()
print(lst1)  # [[1, 2], [3, 4]]

In [ ]:
array_11 = np.array([[5, 2], [7, 4]])
lst2 = list(array_11)
print(lst2)  # [array([5, 2]), array([7, 4])]
print(type(lst2[0]))  # <class 'numpy.ndarray'>

## `Indexing in arrays`

In [ ]:
array_12 = np.array([[1, 12, 31], [4, 45, 64], [0, 7, 89]])
print(array_12[2, 2])  # 89
print(array_12[2][2])  # 89

In [ ]:
array_13 = np.array([[[1, 12, 31], [4, 45, 64], [0, 7, 89]]])
print(array_13[0, 1, 1])  # 45
print(array_13[0][1][1])  # 45

### `Slicing`

In [ ]:
array_14 = np.array([[100, 101, 102],
                 [103, 104, 105],
                 [106, 107, 108],
                 [109, 110, 111]])
print(array_14[1:3, 1])   # [104 107]

In [2]:
import numpy as np 

array = np.linspace(20, 42, num=11)
print(array[4])

28.8


In [10]:
import numpy as np 

# Read four integers from input
nums = [int(input()) for _ in range(4)]

# Create the initial array
initial_array = [[nums[0], nums[1]], [nums[2], nums[3]]]

# Transpose the array

print(np.transpose(initial_array))

[[4 6]
 [5 7]]


In [ ]:
import numpy as np

# Read six integers from input
nums = [int(input()) for _ in range(6)]

# Create the two arrays
matrix = np.array([[nums[0], nums[1]], [nums[2], nums[3]]])
vector = np.array([nums[4], nums[5]])

# Divide the matrix by the vector and transpose the result
result = np.transpose(matrix / vector)

# Print the transposed array
print(result)
